//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CobModel", "FK_CobCopyXRef_CobFile1", "CobFile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(cobinfo.CobFile), "CobFileXRef", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(cobinfo.CobFileXRef), true)]
[assembly: EdmRelationshipAttribute("CobModel", "FK_CobScreen_CobFile", "CobFile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(cobinfo.CobFile), "CobScreen", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(cobinfo.CobScreen), true)]
[assembly: EdmRelationshipAttribute("CobModel", "FK_CobScreenField_CobFile", "CobFile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(cobinfo.CobFile), "CobScreenField", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(cobinfo.CobScreenField), true)]

#endregion

namespace cobinfo
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CobEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CobEntities object using the connection string found in the 'CobEntities' section of the application configuration file.
        /// </summary>
        public CobEntities() : base("name=CobEntities", "CobEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CobEntities object.
        /// </summary>
        public CobEntities(string connectionString) : base(connectionString, "CobEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CobEntities object.
        /// </summary>
        public CobEntities(EntityConnection connection) : base(connection, "CobEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CobFile> CobFiles
        {
            get
            {
                if ((_CobFiles == null))
                {
                    _CobFiles = base.CreateObjectSet<CobFile>("CobFiles");
                }
                return _CobFiles;
            }
        }
        private ObjectSet<CobFile> _CobFiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CobFileXRef> CobFileXRefs
        {
            get
            {
                if ((_CobFileXRefs == null))
                {
                    _CobFileXRefs = base.CreateObjectSet<CobFileXRef>("CobFileXRefs");
                }
                return _CobFileXRefs;
            }
        }
        private ObjectSet<CobFileXRef> _CobFileXRefs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CobScreen> CobScreens
        {
            get
            {
                if ((_CobScreens == null))
                {
                    _CobScreens = base.CreateObjectSet<CobScreen>("CobScreens");
                }
                return _CobScreens;
            }
        }
        private ObjectSet<CobScreen> _CobScreens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CobScreenField> CobScreenFields
        {
            get
            {
                if ((_CobScreenFields == null))
                {
                    _CobScreenFields = base.CreateObjectSet<CobScreenField>("CobScreenFields");
                }
                return _CobScreenFields;
            }
        }
        private ObjectSet<CobScreenField> _CobScreenFields;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CobDDL> CobDDLs
        {
            get
            {
                if ((_CobDDLs == null))
                {
                    _CobDDLs = base.CreateObjectSet<CobDDL>("CobDDLs");
                }
                return _CobDDLs;
            }
        }
        private ObjectSet<CobDDL> _CobDDLs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CobFiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCobFiles(CobFile cobFile)
        {
            base.AddObject("CobFiles", cobFile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CobFileXRefs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCobFileXRefs(CobFileXRef cobFileXRef)
        {
            base.AddObject("CobFileXRefs", cobFileXRef);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CobScreens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCobScreens(CobScreen cobScreen)
        {
            base.AddObject("CobScreens", cobScreen);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CobScreenFields EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCobScreenFields(CobScreenField cobScreenField)
        {
            base.AddObject("CobScreenFields", cobScreenField);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CobDDLs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCobDDLs(CobDDL cobDDL)
        {
            base.AddObject("CobDDLs", cobDDL);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CobModel", Name="CobDDL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CobDDL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CobDDL object.
        /// </summary>
        /// <param name="file_Name">Initial value of the File_Name property.</param>
        /// <param name="field_System_Code">Initial value of the Field_System_Code property.</param>
        /// <param name="field_Name">Initial value of the Field_Name property.</param>
        /// <param name="field_Pic_Txt">Initial value of the Field_Pic_Txt property.</param>
        /// <param name="field_Heading_Txt">Initial value of the Field_Heading_Txt property.</param>
        /// <param name="field_Docs_Txt">Initial value of the Field_Docs_Txt property.</param>
        public static CobDDL CreateCobDDL(global::System.String file_Name, global::System.String field_System_Code, global::System.String field_Name, global::System.String field_Pic_Txt, global::System.String field_Heading_Txt, global::System.String field_Docs_Txt)
        {
            CobDDL cobDDL = new CobDDL();
            cobDDL.File_Name = file_Name;
            cobDDL.Field_System_Code = field_System_Code;
            cobDDL.Field_Name = field_Name;
            cobDDL.Field_Pic_Txt = field_Pic_Txt;
            cobDDL.Field_Heading_Txt = field_Heading_Txt;
            cobDDL.Field_Docs_Txt = field_Docs_Txt;
            return cobDDL;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_Name
        {
            get
            {
                return _File_Name;
            }
            set
            {
                OnFile_NameChanging(value);
                ReportPropertyChanging("File_Name");
                _File_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("File_Name");
                OnFile_NameChanged();
            }
        }
        private global::System.String _File_Name;
        partial void OnFile_NameChanging(global::System.String value);
        partial void OnFile_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Field_System_Code
        {
            get
            {
                return _Field_System_Code;
            }
            set
            {
                OnField_System_CodeChanging(value);
                ReportPropertyChanging("Field_System_Code");
                _Field_System_Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Field_System_Code");
                OnField_System_CodeChanged();
            }
        }
        private global::System.String _Field_System_Code;
        partial void OnField_System_CodeChanging(global::System.String value);
        partial void OnField_System_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Field_Name
        {
            get
            {
                return _Field_Name;
            }
            set
            {
                if (_Field_Name != value)
                {
                    OnField_NameChanging(value);
                    ReportPropertyChanging("Field_Name");
                    _Field_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Field_Name");
                    OnField_NameChanged();
                }
            }
        }
        private global::System.String _Field_Name;
        partial void OnField_NameChanging(global::System.String value);
        partial void OnField_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Field_Pic_Txt
        {
            get
            {
                return _Field_Pic_Txt;
            }
            set
            {
                OnField_Pic_TxtChanging(value);
                ReportPropertyChanging("Field_Pic_Txt");
                _Field_Pic_Txt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Field_Pic_Txt");
                OnField_Pic_TxtChanged();
            }
        }
        private global::System.String _Field_Pic_Txt;
        partial void OnField_Pic_TxtChanging(global::System.String value);
        partial void OnField_Pic_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Field_Heading_Txt
        {
            get
            {
                return _Field_Heading_Txt;
            }
            set
            {
                OnField_Heading_TxtChanging(value);
                ReportPropertyChanging("Field_Heading_Txt");
                _Field_Heading_Txt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Field_Heading_Txt");
                OnField_Heading_TxtChanged();
            }
        }
        private global::System.String _Field_Heading_Txt;
        partial void OnField_Heading_TxtChanging(global::System.String value);
        partial void OnField_Heading_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Field_Docs_Txt
        {
            get
            {
                return _Field_Docs_Txt;
            }
            set
            {
                OnField_Docs_TxtChanging(value);
                ReportPropertyChanging("Field_Docs_Txt");
                _Field_Docs_Txt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Field_Docs_Txt");
                OnField_Docs_TxtChanged();
            }
        }
        private global::System.String _Field_Docs_Txt;
        partial void OnField_Docs_TxtChanging(global::System.String value);
        partial void OnField_Docs_TxtChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CobModel", Name="CobFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CobFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CobFile object.
        /// </summary>
        /// <param name="file_Name">Initial value of the File_Name property.</param>
        /// <param name="file_Prog_Name">Initial value of the File_Prog_Name property.</param>
        /// <param name="file_Type_Code">Initial value of the File_Type_Code property.</param>
        /// <param name="file_Loc_Num">Initial value of the File_Loc_Num property.</param>
        /// <param name="file_Author_Name">Initial value of the File_Author_Name property.</param>
        /// <param name="file_Written_Dt">Initial value of the File_Written_Dt property.</param>
        /// <param name="file_Header_Txt">Initial value of the File_Header_Txt property.</param>
        public static CobFile CreateCobFile(global::System.String file_Name, global::System.String file_Prog_Name, global::System.String file_Type_Code, global::System.Int32 file_Loc_Num, global::System.String file_Author_Name, global::System.String file_Written_Dt, global::System.String file_Header_Txt)
        {
            CobFile cobFile = new CobFile();
            cobFile.File_Name = file_Name;
            cobFile.File_Prog_Name = file_Prog_Name;
            cobFile.File_Type_Code = file_Type_Code;
            cobFile.File_Loc_Num = file_Loc_Num;
            cobFile.File_Author_Name = file_Author_Name;
            cobFile.File_Written_Dt = file_Written_Dt;
            cobFile.File_Header_Txt = file_Header_Txt;
            return cobFile;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_Name
        {
            get
            {
                return _File_Name;
            }
            set
            {
                if (_File_Name != value)
                {
                    OnFile_NameChanging(value);
                    ReportPropertyChanging("File_Name");
                    _File_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("File_Name");
                    OnFile_NameChanged();
                }
            }
        }
        private global::System.String _File_Name;
        partial void OnFile_NameChanging(global::System.String value);
        partial void OnFile_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_Prog_Name
        {
            get
            {
                return _File_Prog_Name;
            }
            set
            {
                OnFile_Prog_NameChanging(value);
                ReportPropertyChanging("File_Prog_Name");
                _File_Prog_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("File_Prog_Name");
                OnFile_Prog_NameChanged();
            }
        }
        private global::System.String _File_Prog_Name;
        partial void OnFile_Prog_NameChanging(global::System.String value);
        partial void OnFile_Prog_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_Type_Code
        {
            get
            {
                return _File_Type_Code;
            }
            set
            {
                OnFile_Type_CodeChanging(value);
                ReportPropertyChanging("File_Type_Code");
                _File_Type_Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("File_Type_Code");
                OnFile_Type_CodeChanged();
            }
        }
        private global::System.String _File_Type_Code;
        partial void OnFile_Type_CodeChanging(global::System.String value);
        partial void OnFile_Type_CodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 File_Loc_Num
        {
            get
            {
                return _File_Loc_Num;
            }
            set
            {
                OnFile_Loc_NumChanging(value);
                ReportPropertyChanging("File_Loc_Num");
                _File_Loc_Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("File_Loc_Num");
                OnFile_Loc_NumChanged();
            }
        }
        private global::System.Int32 _File_Loc_Num;
        partial void OnFile_Loc_NumChanging(global::System.Int32 value);
        partial void OnFile_Loc_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_Author_Name
        {
            get
            {
                return _File_Author_Name;
            }
            set
            {
                OnFile_Author_NameChanging(value);
                ReportPropertyChanging("File_Author_Name");
                _File_Author_Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("File_Author_Name");
                OnFile_Author_NameChanged();
            }
        }
        private global::System.String _File_Author_Name;
        partial void OnFile_Author_NameChanging(global::System.String value);
        partial void OnFile_Author_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_Written_Dt
        {
            get
            {
                return _File_Written_Dt;
            }
            set
            {
                OnFile_Written_DtChanging(value);
                ReportPropertyChanging("File_Written_Dt");
                _File_Written_Dt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("File_Written_Dt");
                OnFile_Written_DtChanged();
            }
        }
        private global::System.String _File_Written_Dt;
        partial void OnFile_Written_DtChanging(global::System.String value);
        partial void OnFile_Written_DtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_Header_Txt
        {
            get
            {
                return _File_Header_Txt;
            }
            set
            {
                OnFile_Header_TxtChanging(value);
                ReportPropertyChanging("File_Header_Txt");
                _File_Header_Txt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("File_Header_Txt");
                OnFile_Header_TxtChanged();
            }
        }
        private global::System.String _File_Header_Txt;
        partial void OnFile_Header_TxtChanging(global::System.String value);
        partial void OnFile_Header_TxtChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CobModel", "FK_CobCopyXRef_CobFile1", "CobFileXRef")]
        public EntityCollection<CobFileXRef> CobFileXRefs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CobFileXRef>("CobModel.FK_CobCopyXRef_CobFile1", "CobFileXRef");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CobFileXRef>("CobModel.FK_CobCopyXRef_CobFile1", "CobFileXRef", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CobModel", "FK_CobScreen_CobFile", "CobScreen")]
        public EntityCollection<CobScreen> CobScreens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CobScreen>("CobModel.FK_CobScreen_CobFile", "CobScreen");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CobScreen>("CobModel.FK_CobScreen_CobFile", "CobScreen", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CobModel", "FK_CobScreenField_CobFile", "CobScreenField")]
        public EntityCollection<CobScreenField> CobScreenFields
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CobScreenField>("CobModel.FK_CobScreenField_CobFile", "CobScreenField");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CobScreenField>("CobModel.FK_CobScreenField_CobFile", "CobScreenField", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CobModel", Name="CobFileXRef")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CobFileXRef : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CobFileXRef object.
        /// </summary>
        /// <param name="xref_File_Name">Initial value of the Xref_File_Name property.</param>
        /// <param name="xref_DependsOnFile_Name">Initial value of the Xref_DependsOnFile_Name property.</param>
        /// <param name="xref_Type_Code">Initial value of the Xref_Type_Code property.</param>
        public static CobFileXRef CreateCobFileXRef(global::System.String xref_File_Name, global::System.String xref_DependsOnFile_Name, global::System.String xref_Type_Code)
        {
            CobFileXRef cobFileXRef = new CobFileXRef();
            cobFileXRef.Xref_File_Name = xref_File_Name;
            cobFileXRef.Xref_DependsOnFile_Name = xref_DependsOnFile_Name;
            cobFileXRef.Xref_Type_Code = xref_Type_Code;
            return cobFileXRef;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Xref_File_Name
        {
            get
            {
                return _Xref_File_Name;
            }
            set
            {
                if (_Xref_File_Name != value)
                {
                    OnXref_File_NameChanging(value);
                    ReportPropertyChanging("Xref_File_Name");
                    _Xref_File_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Xref_File_Name");
                    OnXref_File_NameChanged();
                }
            }
        }
        private global::System.String _Xref_File_Name;
        partial void OnXref_File_NameChanging(global::System.String value);
        partial void OnXref_File_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Xref_DependsOnFile_Name
        {
            get
            {
                return _Xref_DependsOnFile_Name;
            }
            set
            {
                if (_Xref_DependsOnFile_Name != value)
                {
                    OnXref_DependsOnFile_NameChanging(value);
                    ReportPropertyChanging("Xref_DependsOnFile_Name");
                    _Xref_DependsOnFile_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Xref_DependsOnFile_Name");
                    OnXref_DependsOnFile_NameChanged();
                }
            }
        }
        private global::System.String _Xref_DependsOnFile_Name;
        partial void OnXref_DependsOnFile_NameChanging(global::System.String value);
        partial void OnXref_DependsOnFile_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Xref_Type_Code
        {
            get
            {
                return _Xref_Type_Code;
            }
            set
            {
                OnXref_Type_CodeChanging(value);
                ReportPropertyChanging("Xref_Type_Code");
                _Xref_Type_Code = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Xref_Type_Code");
                OnXref_Type_CodeChanged();
            }
        }
        private global::System.String _Xref_Type_Code;
        partial void OnXref_Type_CodeChanging(global::System.String value);
        partial void OnXref_Type_CodeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CobModel", "FK_CobCopyXRef_CobFile1", "CobFile")]
        public CobFile CobFile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CobFile>("CobModel.FK_CobCopyXRef_CobFile1", "CobFile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CobFile>("CobModel.FK_CobCopyXRef_CobFile1", "CobFile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CobFile> CobFileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CobFile>("CobModel.FK_CobCopyXRef_CobFile1", "CobFile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CobFile>("CobModel.FK_CobCopyXRef_CobFile1", "CobFile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CobModel", Name="CobScreen")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CobScreen : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CobScreen object.
        /// </summary>
        /// <param name="file_Name">Initial value of the File_Name property.</param>
        /// <param name="screen_Name">Initial value of the Screen_Name property.</param>
        /// <param name="screen_Num">Initial value of the Screen_Num property.</param>
        /// <param name="screen_IsOverlay_Ind">Initial value of the Screen_IsOverlay_Ind property.</param>
        public static CobScreen CreateCobScreen(global::System.String file_Name, global::System.String screen_Name, global::System.String screen_Num, global::System.Boolean screen_IsOverlay_Ind)
        {
            CobScreen cobScreen = new CobScreen();
            cobScreen.File_Name = file_Name;
            cobScreen.Screen_Name = screen_Name;
            cobScreen.Screen_Num = screen_Num;
            cobScreen.Screen_IsOverlay_Ind = screen_IsOverlay_Ind;
            return cobScreen;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_Name
        {
            get
            {
                return _File_Name;
            }
            set
            {
                if (_File_Name != value)
                {
                    OnFile_NameChanging(value);
                    ReportPropertyChanging("File_Name");
                    _File_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("File_Name");
                    OnFile_NameChanged();
                }
            }
        }
        private global::System.String _File_Name;
        partial void OnFile_NameChanging(global::System.String value);
        partial void OnFile_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Screen_Name
        {
            get
            {
                return _Screen_Name;
            }
            set
            {
                if (_Screen_Name != value)
                {
                    OnScreen_NameChanging(value);
                    ReportPropertyChanging("Screen_Name");
                    _Screen_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Screen_Name");
                    OnScreen_NameChanged();
                }
            }
        }
        private global::System.String _Screen_Name;
        partial void OnScreen_NameChanging(global::System.String value);
        partial void OnScreen_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Screen_Num
        {
            get
            {
                return _Screen_Num;
            }
            set
            {
                OnScreen_NumChanging(value);
                ReportPropertyChanging("Screen_Num");
                _Screen_Num = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Screen_Num");
                OnScreen_NumChanged();
            }
        }
        private global::System.String _Screen_Num;
        partial void OnScreen_NumChanging(global::System.String value);
        partial void OnScreen_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Screen_IsOverlay_Ind
        {
            get
            {
                return _Screen_IsOverlay_Ind;
            }
            set
            {
                OnScreen_IsOverlay_IndChanging(value);
                ReportPropertyChanging("Screen_IsOverlay_Ind");
                _Screen_IsOverlay_Ind = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Screen_IsOverlay_Ind");
                OnScreen_IsOverlay_IndChanged();
            }
        }
        private global::System.Boolean _Screen_IsOverlay_Ind;
        partial void OnScreen_IsOverlay_IndChanging(global::System.Boolean value);
        partial void OnScreen_IsOverlay_IndChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CobModel", "FK_CobScreen_CobFile", "CobFile")]
        public CobFile CobFile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CobFile>("CobModel.FK_CobScreen_CobFile", "CobFile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CobFile>("CobModel.FK_CobScreen_CobFile", "CobFile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CobFile> CobFileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CobFile>("CobModel.FK_CobScreen_CobFile", "CobFile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CobFile>("CobModel.FK_CobScreen_CobFile", "CobFile", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CobModel", Name="CobScreenField")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CobScreenField : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CobScreenField object.
        /// </summary>
        /// <param name="file_Name">Initial value of the File_Name property.</param>
        /// <param name="screen_Name">Initial value of the Screen_Name property.</param>
        /// <param name="field_Name">Initial value of the Field_Name property.</param>
        /// <param name="field_Lvl_Num">Initial value of the Field_Lvl_Num property.</param>
        /// <param name="field_X_Num">Initial value of the Field_X_Num property.</param>
        /// <param name="field_Y_Num">Initial value of the Field_Y_Num property.</param>
        /// <param name="field_Line_Num">Initial value of the Field_Line_Num property.</param>
        public static CobScreenField CreateCobScreenField(global::System.String file_Name, global::System.String screen_Name, global::System.String field_Name, global::System.String field_Lvl_Num, global::System.Int32 field_X_Num, global::System.Int32 field_Y_Num, global::System.Int32 field_Line_Num)
        {
            CobScreenField cobScreenField = new CobScreenField();
            cobScreenField.File_Name = file_Name;
            cobScreenField.Screen_Name = screen_Name;
            cobScreenField.Field_Name = field_Name;
            cobScreenField.Field_Lvl_Num = field_Lvl_Num;
            cobScreenField.Field_X_Num = field_X_Num;
            cobScreenField.Field_Y_Num = field_Y_Num;
            cobScreenField.Field_Line_Num = field_Line_Num;
            return cobScreenField;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String File_Name
        {
            get
            {
                return _File_Name;
            }
            set
            {
                if (_File_Name != value)
                {
                    OnFile_NameChanging(value);
                    ReportPropertyChanging("File_Name");
                    _File_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("File_Name");
                    OnFile_NameChanged();
                }
            }
        }
        private global::System.String _File_Name;
        partial void OnFile_NameChanging(global::System.String value);
        partial void OnFile_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Screen_Name
        {
            get
            {
                return _Screen_Name;
            }
            set
            {
                if (_Screen_Name != value)
                {
                    OnScreen_NameChanging(value);
                    ReportPropertyChanging("Screen_Name");
                    _Screen_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Screen_Name");
                    OnScreen_NameChanged();
                }
            }
        }
        private global::System.String _Screen_Name;
        partial void OnScreen_NameChanging(global::System.String value);
        partial void OnScreen_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Field_Name
        {
            get
            {
                return _Field_Name;
            }
            set
            {
                if (_Field_Name != value)
                {
                    OnField_NameChanging(value);
                    ReportPropertyChanging("Field_Name");
                    _Field_Name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Field_Name");
                    OnField_NameChanged();
                }
            }
        }
        private global::System.String _Field_Name;
        partial void OnField_NameChanging(global::System.String value);
        partial void OnField_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Field_Lvl_Num
        {
            get
            {
                return _Field_Lvl_Num;
            }
            set
            {
                if (_Field_Lvl_Num != value)
                {
                    OnField_Lvl_NumChanging(value);
                    ReportPropertyChanging("Field_Lvl_Num");
                    _Field_Lvl_Num = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Field_Lvl_Num");
                    OnField_Lvl_NumChanged();
                }
            }
        }
        private global::System.String _Field_Lvl_Num;
        partial void OnField_Lvl_NumChanging(global::System.String value);
        partial void OnField_Lvl_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Field_X_Num
        {
            get
            {
                return _Field_X_Num;
            }
            set
            {
                OnField_X_NumChanging(value);
                ReportPropertyChanging("Field_X_Num");
                _Field_X_Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Field_X_Num");
                OnField_X_NumChanged();
            }
        }
        private global::System.Int32 _Field_X_Num;
        partial void OnField_X_NumChanging(global::System.Int32 value);
        partial void OnField_X_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Field_Y_Num
        {
            get
            {
                return _Field_Y_Num;
            }
            set
            {
                OnField_Y_NumChanging(value);
                ReportPropertyChanging("Field_Y_Num");
                _Field_Y_Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Field_Y_Num");
                OnField_Y_NumChanged();
            }
        }
        private global::System.Int32 _Field_Y_Num;
        partial void OnField_Y_NumChanging(global::System.Int32 value);
        partial void OnField_Y_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_Pic_Txt
        {
            get
            {
                return _Field_Pic_Txt;
            }
            set
            {
                OnField_Pic_TxtChanging(value);
                ReportPropertyChanging("Field_Pic_Txt");
                _Field_Pic_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_Pic_Txt");
                OnField_Pic_TxtChanged();
            }
        }
        private global::System.String _Field_Pic_Txt;
        partial void OnField_Pic_TxtChanging(global::System.String value);
        partial void OnField_Pic_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Field_OverlayWidth_Num
        {
            get
            {
                return _Field_OverlayWidth_Num;
            }
            set
            {
                OnField_OverlayWidth_NumChanging(value);
                ReportPropertyChanging("Field_OverlayWidth_Num");
                _Field_OverlayWidth_Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Field_OverlayWidth_Num");
                OnField_OverlayWidth_NumChanged();
            }
        }
        private Nullable<global::System.Int32> _Field_OverlayWidth_Num;
        partial void OnField_OverlayWidth_NumChanging(Nullable<global::System.Int32> value);
        partial void OnField_OverlayWidth_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Field_OverlayHieght_Num
        {
            get
            {
                return _Field_OverlayHieght_Num;
            }
            set
            {
                OnField_OverlayHieght_NumChanging(value);
                ReportPropertyChanging("Field_OverlayHieght_Num");
                _Field_OverlayHieght_Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Field_OverlayHieght_Num");
                OnField_OverlayHieght_NumChanged();
            }
        }
        private Nullable<global::System.Int32> _Field_OverlayHieght_Num;
        partial void OnField_OverlayHieght_NumChanging(Nullable<global::System.Int32> value);
        partial void OnField_OverlayHieght_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_From_Txt
        {
            get
            {
                return _Field_From_Txt;
            }
            set
            {
                OnField_From_TxtChanging(value);
                ReportPropertyChanging("Field_From_Txt");
                _Field_From_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_From_Txt");
                OnField_From_TxtChanged();
            }
        }
        private global::System.String _Field_From_Txt;
        partial void OnField_From_TxtChanging(global::System.String value);
        partial void OnField_From_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_To_Txt
        {
            get
            {
                return _Field_To_Txt;
            }
            set
            {
                OnField_To_TxtChanging(value);
                ReportPropertyChanging("Field_To_Txt");
                _Field_To_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_To_Txt");
                OnField_To_TxtChanged();
            }
        }
        private global::System.String _Field_To_Txt;
        partial void OnField_To_TxtChanging(global::System.String value);
        partial void OnField_To_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_Using_Txt
        {
            get
            {
                return _Field_Using_Txt;
            }
            set
            {
                OnField_Using_TxtChanging(value);
                ReportPropertyChanging("Field_Using_Txt");
                _Field_Using_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_Using_Txt");
                OnField_Using_TxtChanged();
            }
        }
        private global::System.String _Field_Using_Txt;
        partial void OnField_Using_TxtChanging(global::System.String value);
        partial void OnField_Using_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_Attribs_Txt
        {
            get
            {
                return _Field_Attribs_Txt;
            }
            set
            {
                OnField_Attribs_TxtChanging(value);
                ReportPropertyChanging("Field_Attribs_Txt");
                _Field_Attribs_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_Attribs_Txt");
                OnField_Attribs_TxtChanged();
            }
        }
        private global::System.String _Field_Attribs_Txt;
        partial void OnField_Attribs_TxtChanging(global::System.String value);
        partial void OnField_Attribs_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_Upshift_Txt
        {
            get
            {
                return _Field_Upshift_Txt;
            }
            set
            {
                OnField_Upshift_TxtChanging(value);
                ReportPropertyChanging("Field_Upshift_Txt");
                _Field_Upshift_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_Upshift_Txt");
                OnField_Upshift_TxtChanged();
            }
        }
        private global::System.String _Field_Upshift_Txt;
        partial void OnField_Upshift_TxtChanging(global::System.String value);
        partial void OnField_Upshift_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_WhenFull_Txt
        {
            get
            {
                return _Field_WhenFull_Txt;
            }
            set
            {
                OnField_WhenFull_TxtChanging(value);
                ReportPropertyChanging("Field_WhenFull_Txt");
                _Field_WhenFull_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_WhenFull_Txt");
                OnField_WhenFull_TxtChanged();
            }
        }
        private global::System.String _Field_WhenFull_Txt;
        partial void OnField_WhenFull_TxtChanging(global::System.String value);
        partial void OnField_WhenFull_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_WhenAbsent_Txt
        {
            get
            {
                return _Field_WhenAbsent_Txt;
            }
            set
            {
                OnField_WhenAbsent_TxtChanging(value);
                ReportPropertyChanging("Field_WhenAbsent_Txt");
                _Field_WhenAbsent_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_WhenAbsent_Txt");
                OnField_WhenAbsent_TxtChanged();
            }
        }
        private global::System.String _Field_WhenAbsent_Txt;
        partial void OnField_WhenAbsent_TxtChanging(global::System.String value);
        partial void OnField_WhenAbsent_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_WhenBlank_Txt
        {
            get
            {
                return _Field_WhenBlank_Txt;
            }
            set
            {
                OnField_WhenBlank_TxtChanging(value);
                ReportPropertyChanging("Field_WhenBlank_Txt");
                _Field_WhenBlank_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_WhenBlank_Txt");
                OnField_WhenBlank_TxtChanged();
            }
        }
        private global::System.String _Field_WhenBlank_Txt;
        partial void OnField_WhenBlank_TxtChanging(global::System.String value);
        partial void OnField_WhenBlank_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_Fill_Txt
        {
            get
            {
                return _Field_Fill_Txt;
            }
            set
            {
                OnField_Fill_TxtChanging(value);
                ReportPropertyChanging("Field_Fill_Txt");
                _Field_Fill_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_Fill_Txt");
                OnField_Fill_TxtChanged();
            }
        }
        private global::System.String _Field_Fill_Txt;
        partial void OnField_Fill_TxtChanging(global::System.String value);
        partial void OnField_Fill_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_RequiredOptions_Txt
        {
            get
            {
                return _Field_RequiredOptions_Txt;
            }
            set
            {
                OnField_RequiredOptions_TxtChanging(value);
                ReportPropertyChanging("Field_RequiredOptions_Txt");
                _Field_RequiredOptions_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_RequiredOptions_Txt");
                OnField_RequiredOptions_TxtChanged();
            }
        }
        private global::System.String _Field_RequiredOptions_Txt;
        partial void OnField_RequiredOptions_TxtChanging(global::System.String value);
        partial void OnField_RequiredOptions_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Field_RequiredLength_Txt
        {
            get
            {
                return _Field_RequiredLength_Txt;
            }
            set
            {
                OnField_RequiredLength_TxtChanging(value);
                ReportPropertyChanging("Field_RequiredLength_Txt");
                _Field_RequiredLength_Txt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Field_RequiredLength_Txt");
                OnField_RequiredLength_TxtChanged();
            }
        }
        private global::System.String _Field_RequiredLength_Txt;
        partial void OnField_RequiredLength_TxtChanging(global::System.String value);
        partial void OnField_RequiredLength_TxtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Field_Line_Num
        {
            get
            {
                return _Field_Line_Num;
            }
            set
            {
                OnField_Line_NumChanging(value);
                ReportPropertyChanging("Field_Line_Num");
                _Field_Line_Num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Field_Line_Num");
                OnField_Line_NumChanged();
            }
        }
        private global::System.Int32 _Field_Line_Num;
        partial void OnField_Line_NumChanging(global::System.Int32 value);
        partial void OnField_Line_NumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DdlField_Name
        {
            get
            {
                return _DdlField_Name;
            }
            set
            {
                OnDdlField_NameChanging(value);
                ReportPropertyChanging("DdlField_Name");
                _DdlField_Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DdlField_Name");
                OnDdlField_NameChanged();
            }
        }
        private global::System.String _DdlField_Name;
        partial void OnDdlField_NameChanging(global::System.String value);
        partial void OnDdlField_NameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CobModel", "FK_CobScreenField_CobFile", "CobFile")]
        public CobFile CobFile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CobFile>("CobModel.FK_CobScreenField_CobFile", "CobFile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CobFile>("CobModel.FK_CobScreenField_CobFile", "CobFile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CobFile> CobFileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CobFile>("CobModel.FK_CobScreenField_CobFile", "CobFile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CobFile>("CobModel.FK_CobScreenField_CobFile", "CobFile", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
